import "./globals.css";
import { Open_Sans } from "next/font/google";
import Navbar from "@/components/Navbar";
import AuthContext from "@/context/AuthContext";
import SWRConfigContext from "@/context/SWRConfigContext";

const openSans = Open_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={openSans.className}>
      <body className="w-full overflow-auto mx-auto">
        <AuthContext>
          {/* AuthContext로 감싸주었기 때문에 이 하위 요소들에서 useSession기능을 사용할 수 있다. */}
          <header className="sticky top-0 bg-white z-10 border-b">
            <Navbar />
          </header>
          <main>
            <SWRConfigContext>{children}</SWRConfigContext>
          </main>
        </AuthContext>
        <div id="portal" />
        {/* portal 노드 생성 */}
      </body>
    </html>
  );
}
